# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6090d5aec23adb5ebbc395fcae8b1530358b4845cffe663d22eb68bca78c6e9a89634e88f2c94f41968bca12310176b9c7ca91a847f8ed2cb30ee9f09d6a3b98

test:
  secret_key_base: 920f3a50b3c167c4f4aa50bc7e74cc60e0142594835570938873b13f07c948e297d61db9ef788dbf84765b7ec2f32420d817b2961980d8d686dc11f0b0a7c2a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
